services:
  - type: web
    name: news-portal
    runtime: docker
    plan: free
    region: singapore

    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /index.php

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        value: mysql-a6f1cf7-syedminhaz365-1ed6.e.aivencloud.com

      - key: DB_PORT
        value: "11508"

      - key: DB_DATABASE
        value: news_portal

      - key: DB_USERNAME
        value: avnadmin

      - key: DB_PASSWORD
        sync: false